### ISSUE TITLE
Verify searched license locations

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/licenser#4]
This task should verify that all the following locations are searched for licence files:
- package.json file checked first for the <license> tag
- then check README
- then check file with LICENSE in its name
- then check file with COPYING in its name

This should be done be creating a unit test and a mock/dummy project with licenses in the above mentioned locations.

**Comment by helio-frota** [comment]
@danbev seems the current module we are using to search licenses, has some limitations related
to this task.

1. when the code finds a license then stop searching on another files
e.g: license found on COPYING, then not show LICENSE.
the property `licenseFile` is used to this.

the result is only:
```
 { 'sample_project@1.0.0': 
       { licenses: 'MIT',
         publisher: 'foo',
         licenseFile: '/full path here/sample_project/COPYING' } }
```


2. Not able to search on README. 
I mean when using only README (or README.md) it shows always:
`{ 'sample_project@1.0.0': { licenses: 'MIT', publisher: 'foo' } }` without
 `licenseFile` property.

**Comment by danbev** [comment]
@helio-frota Great, exactly what we wanted to find out. 

We can either take a look at an alternative existing license search implementation or perhaps we should write our own for our specific needs. Would you be willing to take a look if there are any other license searching options out there that might fit our needs, and if there are none create an issue for this. We can still make progress on other issue I think but this would be the highest priority one I think.

**Comment by helio-frota** [comment]
@danbev yah sounds good .

**Comment by helio-frota** [comment]
The tool can find the license from `README.md` or `README` when no 'license' property found on package.json.

But still not showing the `licenseFile` property, the result is 
`{ 'sample_dependency@1.0.0': { licenses: 'MIT*' } }` with `*`

-> Maybe <- we can add this property on resulting json, assuming that "when no licenseFile, and *,  then means the license was found on README"

**Comment by helio-frota** [comment]
Also, I'm going to try to make some workaround related to the "Find -> found - > stop searching" behavior.
because we need to continue to satisfy the task

> This task should verify that all the following locations are searched for licence files...

not only one place.

**Comment by helio-frota** [comment]
here we have README on licenseFile:
https://github.com/helio-frota/license-checker/tree/licensefile-readme

sample output:
```
 { 'sample_dependency@1.0.0': 
       { licenses: 'MIT*',
         licenseFile: '/full path here/sample_dependency/README' } }
```

**Comment by helio-frota** [comment]
we need to solve 1 remaining thing:

_to show all license file locations, and not only one file license location._

With the small previous change, when the package.json has `license` property the README is shown on `licenseFile` .

**Comment by helio-frota** [comment]
@danbev 

"This task should verify that all the following locations are searched for licence files:"

This means, **only to search**, I mean to guarantee that it was searched, or means to output also ?

if this is `to ensure that it was searched` then we can close this issue and use my fork (and of course I'll  send a PR to the original repository)

**Comment by danbev** [comment]
> This means, only to search, I mean to guarantee that it was searched, or means to output also ?

I only head verifying in mind and that we'd create a new issue for anything that we discover is missing, like you have done.

Like you said we should probably send a PR upstream and also create a new task so that we can extract the contents of the licence in the README. This is needed because at the moment the entire README will be include in the xml element. Does that make sense?

**Comment by helio-frota** [comment]
https://github.com/davglass/license-checker/pull/106

**Comment by helio-frota** [comment]
this PR covers this task with some tests:
https://github.com/bucharest-gold/licenser/pull/38
